sudo: required
language: go
notifications:
  email: false

go:
- "1.10.x"

cache:
  directories:
  - /home/travis/gopath/src/github.com/uubk/microkube/.deps
  - /home/travis/gopath/src/github.com/uubk/microkube/vendor
  - /home/travis/gopath/pkg/dep

before_install:
# We need glide, etcd, cni-plugins, nsenter and hyperkube
- cd .deps
- wget -qN https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
- wget -qN https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
- wget -qN https://dl.k8s.io/v1.11.2/kubernetes-server-linux-amd64.tar.gz
- wget -qN https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
- sha256sum -c .ci.sha256sum
- mv dep-linux-amd64 $GOPATH/bin/dep && chmod +x $GOPATH/bin/dep
- cd ..
- mkdir third_party
- tar -xf .deps/kubernetes-server-linux-amd64.tar.gz
- tar -xf .deps/etcd-v3.3.9-linux-amd64.tar.gz
- mv kubernetes/server/bin/hyperkube third_party
- mv etcd-v3.3.9-linux-amd64/etcd third_party
- rm -Rf kubernetes
- rm -Rf etcd-v3.3.9-linux-amd64
- cd third_party && tar -xvf ../.deps/cni-plugins-amd64-v0.7.1.tgz && rm ../.deps/cni-plugins-amd64-v0.7.1.tgz && cd ..
- docker run --rm -v /usr/bin:/target jpetazzo/nsenter

script:
- go test -race -coverprofile=cover1 -covermode=atomic -run 'Test[^9]' -v ./...
- sudo killall etcd || /bin/true
- sudo killall hyperkube || /bin/true
- sudo rm -Rf /tmp/microkube* || /bin/true
- go test -coverprofile=cover2 -covermode=atomic -run 'Test9' -v ./...

install:
- dep ensure

after_success:
- cat cover1 cover2 > coverage.txt
- bash <(curl -s https://codecov.io/bash)