sudo: required
language: go
notifications:
  email: false

go:
- "1.10.x"

matrix:
  include:
  - env: PACKAGE=Yes
    if: branch =~ ^release
  - env: PACKAGE=No
    if: branch !~ ^release

cache:
  directories:
  - /home/travis/gopath/src/github.com/vs-eth/microkube/.deps
  - /home/travis/gopath/src/github.com/vs-eth/microkube/vendor

before_install:
# We need glide, etcd, cni-plugins, nsenter and hyperkube
- cd .deps
- wget -q -nc https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
- wget -q -nc https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
- wget -q -nc https://dl.k8s.io/v1.11.2/kubernetes-server-linux-amd64.tar.gz
- wget -q -nc https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
- sha256sum -c .ci.sha256sum
- mv dep-linux-amd64 $GOPATH/bin/dep && chmod +x $GOPATH/bin/dep
- cd ..
- mkdir third_party
- tar -xf .deps/kubernetes-server-linux-amd64.tar.gz
- tar -xf .deps/etcd-v3.3.9-linux-amd64.tar.gz
- mv kubernetes/server/bin/hyperkube third_party
- mv etcd-v3.3.9-linux-amd64/etcd third_party
- rm -Rf kubernetes
- rm -Rf etcd-v3.3.9-linux-amd64
- cd third_party && tar -xvf ../.deps/cni-plugins-amd64-v0.7.1.tgz && rm ../.deps/cni-plugins-amd64-v0.7.1.tgz && cd ..
- docker run --rm -v /usr/bin:/target jpetazzo/nsenter

script:
- export PACKAGE && ./.travis.sh

install:
- dep ensure
- go get -u github.com/sirkon/ldetool
- make generate

deploy:
  provider: releases
  api_key:
    secure: hB4kjBLpr6+j7IRuqIP9DyqwJc6BuSZBtpDDwngDqRxGjtyMxj8TbgqM5OFx9xxECwh2UJ2zu/fyCVJv6tfEBHtjcDHH7OEgoXXw12Y4jR5Wi97J3NuXmFuXzT3elwhU0EqFTu7mn1ZkO2H33OWCijWZdpFGR9DGu5EeTOR3exSSRkSw+lbdPynkta3OL+g6SlgmhVcQpgCGF5KGbYQwwq184Ltyb4+3Wc3WibGGhnm7ZBblaTk6FntRKUD34kr1CMAP4OtxyriixRmHAHa1UfRQMoAeMM6ZvwsGfUj1LmH04kO4FOZXKLkqHIP2Y33pUD+ppIIn9XGLw6HXJIRKllxlbsQdIiZXreycPC5Kp7WcRdy2HRr97r4m7q5KCEWm0C8h/ElVqaFcyIjoHoPariLId+F0bJy7G6s411WiAE9dGgJ2nGeKhSEi7RNL29bre5ZCSsng1Vl9MfhBFBe/S9RtE2qlZ1V/pe3+awBraq5aXHw7bVucHkYfWGOMEVPC2wV3US4o2W3Oo08jxc9PWHGGJOlAl/0iCsxHvwkpNjwuo1kKxjeCGA3FNddr+IzLpfcQvjm1sTZerghtnJsUfhvdJS1KOiBRF/GW8U/zZEhXB34YK6EjkZgtR6H11s+6KyS/kRBT0GGFGof70SdFbOc9/PZ5mdtip0kazFf4aeY=
  file: "../microkube*deb"
  file_glob: true
  on:
    repo: vs-eth/microkube
    tags: true
