#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd mukube > /dev/null ; then
            adduser --system --group --no-create-home --disabled-login --home /var/lib/mukube mukube
        fi
        chown mukube:mukube /var/lib/mukube
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
