/*
 * THIS FILE IS AUTOGENERATED by github.com/uubk/microkube/cmd/codegen/Manifest.go
 * DO NOT TOUCH.
 * In case of issues, please fix the code generator ;)
 */

package main

import (
	"github.com/uubk/microkube/pkg/manifests"
)

func main() {
	obj := manifests.NewDNS()
	obj.ApplyToCluster("/home/maxf/.mukube/kube/kubeconfig")
}
